baseURL = "https://artemiscloud.github.io/website/"
title = "Artemis Cloud"
theme = "artemiscloudtheme"
languageName = "En"
languageCode = "en-us"

# post pagination
paginate = "3"

# post excerpt
summaryLength = "15"

# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com

# google analytics
googleAnalytics = "" # example : UA-123-45

# unsafe html
[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"


############################## navigation ###############################

# main menu
[[menu.main]]
name = "Home"
URL = "/"
weight = 1

[[menu.main]]
name = "Blog"
URL = "blog"
weight = 2

[[menu.main]]
name = "Documentation"
URL = "documentation"
weight = 3

[[menu.main]]
name = "Releases"
URL = "releases"
weight = 4

[[menu.main]]
name = "Community"
URL = "community"
weight = 5

#################### default parameters ################################
[params]
logo = "images/logo.png"
logo2 = "images/logo2.png"
logo_width = "250px"
logo2_width = "75px"
# Meta data
description = "This is meta description"
author = "Themefisher"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io

########### footer content ##########
#footer_menu_left = "Company"
#footer_menu_middle = "Product"
#footer_menu_right = "Support"
footer_title = "ArtemisCloud"
footer_content = "Follow us on social"
# copyright
copyright = "All code and documentation is licensed under the Apache License version 2.0. Marks may be trademarks or registered trademarks of their respective owners."

# Preloader
[params.preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

############################# social site ########################
[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/artemiscloudio"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/ArtemisCloud"
